### ISSUE TITLE
MessagePicturesLayout图片可能不显示的问题

### ISSUE THREAD

**Issue by Jeff-bai** [iielse/ImageWatcher#11]
MessagePicturesLayout显示图片的时候，第一次能出现图片，第二次以后基本绘制不出图片。

**Comment by LengM** [comment]
也有一样的问题。。

**Comment by LengM** [comment]
清理以下Glide缓存就好了

**Comment by MikiHu** [comment]
怎么清理Glide缓存啊

**Comment by iielse** [comment]
github搜索这个 `HighPerformanceFriendsCircle`
9宫格图片展示推荐用这个项目里面的实现方法。 
代码可以下载运行，我试过效果非常不错哇。

**Comment by iielse** [comment]
之前demo中没有添加下拉刷新， 所以大家所说的刷新图片第二次不绘制，在demo中没有出现过。
现在，我在demo一种的顶部加入了数据刷新功能，但是依旧无法复现(小米和华为，3台测试机)。
那么各位在集成`MessagePicturesLayout`时的刷新的方式可能和我不一样？

```
findViewById(R.id.vRefresh).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toast.makeText(v.getContext().getApplicationContext(), "刷新列表内容 adapter.reset()" , Toast.LENGTH_SHORT).show();
                adapter.set(Data.get());
            }
        });
```

其实就是再次调用 `adapter.notifyDataSetChanged()`

可以尝试新的demo代码吗？ @MikiHu  @LengM  @Jeff-bai  @xiong5201314 @gandesheng

![7e5a5592a790451bf5fcdda9786366c5](https://user-images.githubusercontent.com/7521943/43629084-ca65b8bc-972e-11e8-9723-b822ba4e4777.jpg)

点击顶部蓝色区域。 

谢谢，有空请告诉我结果~

同时这里有一个性能更好的 九宫格 ， 了解一下
https://github.com/KCrason/HighPerformanceFriendsCircle/blob/master/app/src/main/java/com/kcrason/highperformancefriendscircle/widgets/NineGridView.java

**Comment by xujiaji** [comment]
本来想换，不过更麻烦，于是看了下是因为第一次显示`set VISIBLE`还没来得及测量。
将`MessagePicturesLayout`构造方法中的`squareImageView.setVisibility(View.GONE);`注释掉就可以了。
