### ISSUE TITLE
有的时候图片不显示

### ISSUE THREAD

**Issue by gandesheng** [iielse/ImageWatcher#19]
显示出来的时候onSizeChanged方法走两次，不显示的时候走一次

**Comment by gandesheng** [comment]
我用ImageLoader加载时，图片不能缓存到SD卡，一旦缓存就会出现偶尔加载不出来的情况

**Comment by iielse** [comment]
嗯，我这边也感觉到类似问题了。 好像是那个图片路径不能访问，是android 7.0 的文件权限问题吗？我再研究研究

**Comment by gandesheng** [comment]
我那个测试机是5,0的

**Comment by gandesheng** [comment]
我觉得应该是缓存问题

**Comment by MikiHu** [comment]
这个问题怎么解决啊？

**Comment by iielse** [comment]
github搜索这个 `HighPerformanceFriendsCircle`
9宫格图片展示推荐用这个项目里面的实现方法。 
代码可以下载运行，我试过效果非常不错哇。

**Comment by iielse** [comment]
https://github.com/iielse/ImageWatcher/issues/11
重复问题
