### ISSUE TITLE
fragment之间hide和show，两个fragment都有MessagePicturesLayout是后一个首次显示是图片绘制不出来

### ISSUE THREAD

**Issue by weiandebeiying** [iielse/ImageWatcher#20]
fragment之间hide和show，两个fragment都有MessagePicturesLayout是后一个首次显示是图片绘制不出来

**Comment by iielse** [comment]
MessagePicturesLayout 不显示图片
https://github.com/iielse/ImageWatcher/issues/11
重复问题
