### ISSUE TITLE
支持WebView中的图片吗

### ISSUE THREAD

**Issue by zhangguobing** [iielse/ImageWatcher#29]
你好，请问WebView中的图片能否实现类似的效果吗

**Comment by ljackChen001** [comment]
同问

**Comment by iielse** [comment]
WebView中拿不到`Drawable`对象吧。 
其实这个库的启动动画说白了需要 一个`Drawable`对象且知道它在屏幕上的坐标，大小。

只有url的话可以这样试试，牺牲掉过渡动画的效果。
临时方案：
随便找一个`ImageView`传递进来，这个ImageView持有一个透明的Drawable对象。
