### ISSUE TITLE
手势中可能出现空指针

### ISSUE THREAD

**Issue by caiyoufei** [iielse/ImageWatcher#31]
![qq 20180809181203](https://user-images.githubusercontent.com/11989916/43893057-4f0d3844-9c00-11e8-9e54-5243188f878c.png)

**Comment by caiyoufei** [comment]
@ielse 不急，随时改都可以的

**Comment by caiyoufei** [comment]
@ielse 正常加载最后一张图，再往左滑动，执行了手势操作，导致界面半黑屏

**Comment by caiyoufei** [comment]
偶发出现卡主的情况：
![qq 20180809204215](https://user-images.githubusercontent.com/11989916/43899821-b61b95e8-9c15-11e8-997f-ba50a18ecd09.png)

**Comment by iielse** [comment]
会出1.1.2 最近很忙
