### ISSUE TITLE
 .setIndexProvider(new DotIndexProvider())不显示,哪些情况下会不显示?

### ISSUE THREAD

**Issue by KiWiLss** [iielse/ImageWatcher#34]

**Comment by iielse** [comment]
![11](https://user-images.githubusercontent.com/7521943/44315531-c3452a00-a457-11e8-9887-02abad7f5afb.gif)

`demo4 MainActivity4`

https://github.com/iielse/ImageWatcher/blob/master/app/src/main/java/ch/ielse/demo/p02/MainActivity4.java#L82

@KiWiLss  这里有个自定义的demo。以上是运行效果。如果你要的就是这个效果，先了解一些。
