### ISSUE TITLE
图片下拉退出有时候回不灵

### ISSUE THREAD

**Issue by xwtao** [iielse/ImageWatcher#36]

**Comment by Sforllln** [comment]
我也有 发现这个问题 能否指点修改一下

**Comment by Sforllln** [comment]
会不会是我没有 设置statusBar 高度的问题啊 我直接填的0

**Comment by iielse** [comment]
你再看看， demo1里面是普通的状态栏， demo2 是透明状态栏。
我自己尝试得时候没有说，下拉会不灵。 可能没有触发你所表达的“有时候”，所以希望能把那个“有时候 ”的流程说一下。
我自己只知道 会有一种“不灵” 
是下拉的时候是原图状态，然后这个时候 手指有点带X轴移动多了点，触发了viewpager的翻页？
如果不灵了，尝试不要松手指，大幅度左右滑动，看看是不是在切换图片。如果是的话，那就是这种不灵了。

对于这个问题，很久之后，我应该会稍稍调节下参数来让触摸更舒服。 还有一些其它触摸细节的可以优化。  这句话的关键是 很久之后/doge。

**Comment by Sforllln** [comment]
好的,我先看看,谢谢你
