### ISSUE TITLE
这一行会有空指针异常

### ISSUE THREAD

**Issue by Aaronjoor** [iielse/ImageWatcher#37]
<img width="528" alt="c6e19951-3765-455d-a982-b5e2b04aa26d" src="https://user-images.githubusercontent.com/11911745/45076989-8303ce00-b11e-11e8-9ddd-972381cf5ec2.png">

**Comment by iielse** [comment]
收到、 下次更新的时间会很久。 现自己弄一下， 谢谢反馈

**Comment by iielse** [comment]
detachedParent 逻辑有问题，记下了。 请问，有固定的复现方法吗？  偶显？

**Comment by iielse** [comment]
原因getParent 为空吧。 看了下逻辑，  加个非空就好了 。
没有细分析， 等我更新，

**Comment by iielse** [comment]
哇，6点了，我以为才下午3点。 先撤了， 会发包的。
我先把改动放这里吧：
1. 提供show(List<Uri> data)  的方法，  【没有入场动画】
2. 提供fragment中使用的demo。
3. 提供添加显示本地图片的demo。 （顺便了解下，有人反馈的本地有bug）
4. 优化下下拽返回不灵的手势（解决和viewpager的横向滑动冲突）。
5. 有些地方(操作) fling效果不好，优化一下。

时间：短则1周，长则1年。看吧，会尽快的。
