### ISSUE TITLE
能不能更改，预览图片的背景颜色？

### ISSUE THREAD

**Issue by FY6** [iielse/ImageWatcher#38]

**Comment by iielse** [comment]
ImageWatcher.setBackgroundColor 可以吗？ 试试、没注意

**Comment by iielse** [comment]
哦，尴尬了，写死的。
`animBackgroundTransform(0xFF000000, 0);`

**Comment by FY6** [comment]
我已经改好了

**Comment by FY6** [comment]
库写的挺不错的，后期还维护吗？我有个建议：你这个库仅仅是在Activity中使用，如果在Fragment中还要各种回调或暴露接口在Activity操作，如果把预览界面做成弹窗，就不会出现这种现象
