### ISSUE TITLE
 iwHelper.show((ImageView) view, mappingViews, pictureList);第一个参数的问题

### ISSUE THREAD

**Issue by zouzhigang** [iielse/ImageWatcher#43]
iwHelper.show((ImageView) view, mappingViews, pictureList); 第一参数如果是android.support.v7.widget.AppCompatImageView 的话， 调用不起来。 换成android.widget.ImageView的就可以。
![_45b995b3-1bc6-4052-b37c-8f03bcf2c656](https://user-images.githubusercontent.com/6103587/45410067-742f9500-b6a3-11e8-89d7-696c8c21e786.png)

**Comment by iielse** [comment]
我现在正在抽时间改框架， `AppCompatImageView` 我会尝试一下的。谢谢反馈
