### ISSUE TITLE
请问在fragment点击返回键如何退出图片

### ISSUE THREAD

**Issue by karmalove** [iielse/ImageWatcher#44]

**Comment by iielse** [comment]
```

    @Override
    public void onBackPressed() {
        if (!iwHelper.handleBackPressed()) {
            super.onBackPressed();
        }
    }
```

**Comment by hu670014125** [comment]
你试试：
fragment中
  @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View rootView = inflater.inflate(R.layout.fragment_demo6, container, false);
        //得到Fragment的根布局并使该布局可以获得焦点
        rootView.setFocusableInTouchMode(true);
        //得到Fragment的根布局并且使其获得焦点
        rootView.requestFocus();
        //对该根布局View注册KeyListener的监听
        rootView.setOnKeyListener(this);
        this.initView(rootView);
        return rootView;
    }

 @Override
    public boolean onKey(View v, int keyCode, KeyEvent event) {
        return keyCode == KeyEvent.KEYCODE_BACK && event.getAction() == KeyEvent.ACTION_DOWN && iwHelper.handleBackPressed();
    }

**Comment by iielse** [comment]
demo 6

**Comment by karmalove** [comment]
thanks

**Comment by WangChangQin** [comment]
@ielse demo 6在哪里啊

**Comment by Munccccc** [comment]
@Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_BACK) {
            if (!iwHelper.handleBackPressed()) {//如果是隐藏状态则退出
                finish();
            }
            return true;
        }
        return super.onKeyDown(keyCode,event);
    }
