### ISSUE TITLE
横向超长图片双击无法看清楚的问题

### ISSUE THREAD

**Issue by hu670014125** [iielse/ImageWatcher#45]
横向超长图片双击无法看清楚的问题
比如：http://image.xcar.com.cn/attachments/a/day_20141126/2014112609_68d9843ed0c3e1d05735CObUWVqIy3rr.jpg
这个长图，双击根本看不清楚
修复代码：
ImageWatcher.java->handleDoubleTapTouchResult()

if (vsCurrent.scaleY <= vsDefault.scaleY && vsCurrent.scaleX <= vsDefault.scaleX) {

            final String imageOrientation = (String) iSource.getTag(R.id.image_orientation);
            float expectedScale = (MAX_SCALE - vsDefault.scaleX) * 0.4f + vsDefault.scaleX;
            if (imageOrientation.equals("horizontal")) {
                ViewState viewState = ViewState.read(iSource, ViewState.STATE_DEFAULT);
                //图片在双击的时候放大的倍数，如果图片过长看不放大根本看不见
                final float scale = viewState.width / viewState.height;
                float maxScale = MAX_SCALE;
                if (scale > 2.0f) {
                    maxScale = MAX_SCALE * scale / 2;
                }
                expectedScale = (maxScale - vsDefault.scaleX) * 0.4f + vsDefault.scaleX;
            }

            animSourceViewStateTransform(iSource, ViewState.write(iSource, ViewState.STATE_TEMP).scaleX(expectedScale).scaleY(expectedScale));
        } else {
            animSourceViewStateTransform(iSource, vsDefault);
        }

希望可以请求合并

**Comment by iielse** [comment]
谢谢，我试试

**Comment by iielse** [comment]
我想了一下 这个缩放比例  最好是，能让双击后， 展示的高度 等于 屏幕高度， 就完美了。
我在研究一下， 还有 fling 好像也有点问题。

**Comment by hu670014125** [comment]
这个是可以的
`ViewState viewState = ViewState.read(iSource, ViewState.STATE_DEFAULT);
            //图片在双击的时候放大的倍数，如果图片过长看不放大根本看不见
            final float scale = viewState.width / viewState.height;
            float maxScale = MAX_SCALE;
            if (scale > 2.0f) {
                maxScale = MAX_SCALE * scale / 2;
            }
            expectedScale = (maxScale - vsDefault.scaleX) * 0.4f + vsDefault.scaleX;`
`  maxScale = MAX_SCALE * scale / 2;`
不除2就等屏幕高度了，但是可能会模糊所以我测试的时候才除2的

**Comment by iielse** [comment]
tab 键上面有个点  连续写3个 ， 把代码框起来 可以排版

**Comment by iielse** [comment]
已经把逻辑合到源码里，下次你可以pull 啊
